import Image from "./Assets/6c757d.jpeg";
const Data = {
  product: [
    {
      id: 1,
      img: { Image },
      Name: "Fancy Product",
      Pricerange: "$40.00 -",
      Price2: "$80.00",
      Button1: "Remove to cart",
      Button: "Add to cart",
    },
    {
      id: 2,
      img: { Image },
      Name: "Special Item",
      Price1: "$20.00",
      Price2: "$18.00",
      Button1: "Remove to cart",
      Button: "Add to cart",
    },
    {
      id: 3,
      img: { Image },
      Name: "Sale Item",
      Price1: "$50.00",
      Price2: "$25.00",
      Button1: "Remove to cart",
      Button: "Add to cart",
    },
    {
      id: 4,
      img: { Image },
      Name: "Popular Item",
      Price2: "$40.00",
      Button1: "Remove to cart",
      Button: "Add to cart",
    },
    {
      id: 5,
      img: { Image },
      Name: "Sale Item",
      Price1: "$50.00",
      Price2: "$25.00",
      Button1: "Remove to cart",
      Button: "Add to cart",
    },
    {
      id: 6,
      img: { Image },
      Name: "Fancy Product",
      Pricerange: "$120.00 -",
      Price2: "$280.00",
      Button1: "Remove to cart",
      Button: "Add to cart",
    },
    {
      id: 7,
      img: { Image },
      Name: "Special Item",
      Price1: "$20.00",
      Price2: "$18.00",
      Button1: "Remove to cart",
      Button: "Add to cart",
    },
    {
      id: 8,
      img: { Image },
      Name: "Popular Item",
      Price2: "$40.00",
      Button1: "Remove to cart",
      Button: "Add to cart",
    },
  ],
};
export default Data;
